name: CI for Repository Dispatch

on:
  repository_dispatch:
    types: ['test_dispatch']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show received client_payload
        env:
          CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "Client Payload"
          echo "$CLIENT_PAYLOAD"
